---
- name: Avi Controller | Requirements | systemd | Check the avicontroller service exist
  ansible.builtin.stat:
    path: /etc/systemd/system/avicontroller.service
  register: service_status

- name: Avi Controller | Requirements | systemd | Stop the avicontroller service for fresh install
  ansible.builtin.systemd:
    daemon_reload: true
    name: avicontroller
    enabled: false
    state: stopped
  when: ansible_service_mgr == 'systemd' and service_status.stat.exists

- name: Avi Controller | Requirements | Clean directories for fresh install
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  when: item != None
  loop:
    - "{{ con_disk_path }}"
    - "{{ con_metrics_disk_path }}"
    - "{{ con_logs_disk_path }}"
