---
- name: Avi Controller | Services | systemd | Check if Avi Controller installed
  ansible.builtin.include_tasks: "services/systemd/check.yml"
  when: ansible_service_mgr == "systemd"

- name: Avi Controller | Services | systemd | Install the Avi Controller service
  when: not avi_installed.stat.exists or con_force_deploy or con_fresh_install
  block:
    - name: Avi Controller | Check minimum requirements
      ansible.builtin.import_tasks: con_requirements.yml

    - name: Avi Controller | Perform specific os tasks
      ansible.builtin.import_tasks: "{{ item }}"
      with_first_found:
        - os/{{ ansible_distribution | lower }}.yml
        - os/default.yml

    - name: Avi Controller | Perform specific os family tasks
      ansible.builtin.import_tasks: "{{ item }}"
      with_first_found:
        - family/{{ ansible_os_family | lower }}.yml
        - family/default.yml

    - name: Avi Controller | Copy setup.json to controller
      ansible.builtin.copy:
        src: "{{ con_setup_json }}"
        dest: "{{ con_disk_path }}/setup.json"
        owner: root
        group: root
        mode: '0600'
      when: con_setup_json != None

    - name: Avi Controller | Copy setup.json to controller
      ansible.builtin.copy:
        content: "{{ con_setup_json_raw | to_json }}\n"
        dest: "{{ con_disk_path }}/setup.json"
        owner: root
        group: root
        mode: '0600'
      when: con_setup_json_raw != None

    # We must do this step first just in case we need to override defaults from the supplied package
    - name: Avi Controller | Docker | Package Deploy
      ansible.builtin.import_tasks: package_deploy.yml
      when: con_package_deploy

    - name: Avi Controller | Docker | Check if specified image already exists.
      ansible.builtin.command: "docker images -q {{ con_image }}"
      changed_when: false
      register: con_docker_match

    - name: Avi Controller | Docker | Check if image exists
      when: not con_package_deploy
      block:
        - name: Avi Controller | Docker | Docker Hub
          ansible.builtin.import_tasks: docker_hub.yml
          when: con_docker_repo == None
        - name: Avi Controller | Docker | Custom Repo
          ansible.builtin.import_tasks: custom_repo.yml
          when: con_docker_repo != None

    - name: Avi Controller | Docker | Cleanup
      ansible.builtin.import_tasks: services/cleanup.yml

    - name: Avi Controller | Docker | Install the Avi Controller services
      ansible.builtin.import_tasks: services/install.yml
