---
- name: Avi Controller | Services | Install the Avi Controller service file | New
  ansible.builtin.template:
    src: avicontroller.j2
    dest: /usr/sbin/avicontroller
    mode: "0750"
    owner: root
    group: root
  notify: Avi Controller | Services | Restart the avicontroller service

- name: Avi Controller | Services | Install the Avi Controller service | New| {{ ansible_service_mgr }}
  ansible.builtin.include_tasks: "{{ ansible_service_mgr }}/install.yml"

- name: Avi Controller | Services | Start the service since it's not running | {{ ansible_service_mgr }}
  ansible.builtin.service:
    name: avicontroller
    enabled: true
    state: started
  when: not con_desired_running.stdout
