---
galaxy_info:
  role_name: avicontroller
  author:
  - Anurag Palsule <anurag.palsule@broadcom.com>
  - Parikshit Manur <parikshit.manur@broadcom.com>
  description: Deploy's the AVI Vantage Controller
  company: VMware
  issue_tracker_url: https://github.com/vmware/ansible-collection-alb/issues
  license: Apache-2.0
  min_ansible_version: 2.15.0
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
  galaxy_tags:
    - avi
    - controller
    - loadbalancer
    - avinetworks
    - avicontroller
    - centos
    - ubuntu
    - mesos
dependencies: []
