---
- name: Check if avise present on host
  ansible.builtin.shell: >
    set -o pipefail && \
    {{ se_deploy_type }} ps | grep avise | wc -l || true
  args:
    executable: /bin/bash
  register: present
  changed_when: false
  become: true

- name: Avise present, set values for used disks info
  when: present.stdout|int == 1
  become: true
  block:
    - name: Avise present, set values for used disks info
      ansible.builtin.shell: >
        set -o pipefail && \
        {{ se_deploy_type }} inspect avise | grep ':/vol/' || true
      args:
        executable: /bin/bash
      changed_when: false
      register: check_dir
    - name: Read system disk path
      ansible.builtin.shell: >
        set -o pipefail && \
        docker inspect avise | grep ":/vol/" | cut -d ':' -f 1 | sed s/\"//g || true
      args:
        executable: /bin/bash
      changed_when: false
      register: u_sysdisk_path
      when: check_dir.rc == 0 and se_deploy_type == "docker"

    - name: Read system disk path
      ansible.builtin.shell: >
        set -o pipefail && \
        podman inspect avise | grep ":/vol/" | cut -d ':' -f 1 | sed s/\"//g || true
      args:
        executable: /bin/bash
      changed_when: false
      register: u_sysdisk_path
      when: check_dir.rc == 0 and se_deploy_type == "podman"

    - name: Get mount point for system disk
      ansible.builtin.shell: >
        set -o pipefail && \
        df {{ u_sysdisk_path.stdout }} -P | tail -n +2 | awk '{print $NF}'
      args:
        executable: /bin/bash
      changed_when: false
      register: u_sysdisk_mount
      when: check_dir.rc == 0 and u_sysdisk_path.stdout is defined

    - name: Read logs directory
      ansible.builtin.shell: >
        set -o pipefail && \
        {{ se_deploy_type }} inspect avise | grep ':/vol_logs/' || true
      args:
        executable: /bin/bash
      changed_when: false
      register: check_dir

    - name: Read logs disk path
      ansible.builtin.shell: >
        set -o pipefail && \
        docker inspect avise | grep ":/vol_logs/" | cut -d ':' -f 1 | sed s/\"//g || true
      args:
        executable: /bin/bash
      changed_when: false
      register: u_logdisk_path
      when: check_dir.rc == 0 and se_deploy_type == "docker"

    - name: Read logs disk path
      ansible.builtin.shell: >
        set -o pipefail && \
        podman inspect avise | grep ":/vol_logs/" | cut -d ':' -f 1 | sed s/\"//g || true
      args:
        executable: /bin/bash
      register: u_logdisk_path
      changed_when: false
      when: check_dir.rc == 0 and se_deploy_type == "podman"

    - name: Get mount point for logs disk
      ansible.builtin.shell: >
        set -o pipefail && \
        df {{ u_logdisk_path.stdout }} -P | tail -n +2 | awk '{print $NF}'
      args:
        executable: /bin/bash
      changed_when: false
      register: u_logdisk_mount
      when: check_dir.rc == 0 and u_logdisk_path.stdout is defined

- name: Avise present, set values for used logs info
  when: not se_dest_disk
  block:
    - name: Get default largest disk for loading SE system partition
      ansible.builtin.shell: >
        set -o pipefail && \
        df -lTP | tail -n +2 | egrep -v 'tmpfs|overlay' | sort -k 5,5 -nr | awk 'NR==1{print $NF}' || true
      args:
        executable: /bin/bash
      register: result
      changed_when: false
    - name: "Set se destination disk"
      ansible.builtin.set_fact:
        se_dest_disk: "{{ result.stdout }}"

- name: Set se disk size in gb
  ansible.builtin.set_fact:
    se_disk_gb: "{{ s_disk_gb }}"
  when: s_disk_gb|int > 0

- name: Set se logs disk size
  ansible.builtin.set_fact:
    se_logs_disk_gb: "{{ s_logs_disk_gb }}"
  when: s_logs_disk_gb|int > 0

- name: "Check status {{ se_dest_disk }}"
  ansible.builtin.stat:
    path: "{{ se_dest_disk }}"
  register: st
  when: se_dest_disk and se_dest_disk|string

- name: Check if logs directory exists
  block:
    - name: Set error message
      ansible.builtin.set_fact:
        error_string: "Directory path {{ se_dest_disk }} specified for system logs does not exist"
    - name: Include error.yml
      ansible.builtin.include_tasks: error.yml
      when: se_dest_disk and se_dest_disk|string  and (not st.stat.exists or not st.stat.isdir)

- name: "Check status of {{ se_destination_log_disk }}"
  ansible.builtin.stat:
    path: "{{ se_destination_log_disk }}"
  register: st
  when: se_destination_log_disk and se_destination_log_disk|string

- name: Set error message
  block:
    - name: Set error message
      ansible.builtin.set_fact:
        error_string: "Directory path {{ se_destination_log_disk }} specified for client logs does not exist"
    - name: Include error.yml
      ansible.builtin.include_tasks: error.yml
      when: se_destination_log_disk and se_destination_log_disk|string and (not st.stat.exists or not st.stat.isdir)

- name: Check service engine disk
  when: se_dest_disk and se_dest_disk|string
  block:
    - name: Get mount point for sys disk
      ansible.builtin.shell: >
        set -o pipefail && \
        df {{ se_dest_disk }} -P | tail -n +2 | awk '{print $NF}'
      args:
        executable: /bin/bash
      changed_when: false
      register: se_disk_mount
    - name: Get disk space on service engine disk path
      ansible.builtin.shell: >
        set -o pipefail && \
        df {{ se_disk_mount.stdout }} -BG -P | grep -iv Used | awk '{print $4}' | sed s/G//g || true
      args:
        executable: /bin/bash
      changed_when: false
      register: se_disk_path_space

- name: Check service engine disk usage
  when: u_sysdisk_mount.stdout is defined and se_disk_mount.stdout is defined and u_sysdisk_mount.stdout == se_disk_mount.stdout
  become: true
  block:
    - name: Axecute docker container
      ansible.builtin.command: "{{ se_deploy_type }} exec avise du -s -BG /vol/"
      changed_when: false
      register: check_dir
    - name: Execute docker container
      changed_when: false
      ansible.builtin.shell: >
        set -o pipefail && \
        {{ se_deploy_type }} exec avise du -s -BG /vol/ | awk '{print $1}' | sed s/G//
      args:
        executable: /bin/bash
      register: temp
      when: check_dir.rc == 0
    - name: Set se_used_sysdisk
      ansible.builtin.set_fact:
        se_used_sysdisk: "{{ temp.stdout }}"
      changed_when: false
      when: check_dir.rc == 0

- name: Check service engine disk usage
  when: se_dest_disk and se_dest_disk|string and (se_disk_path_space.stdout|int + se_used_sysdisk|int) < se_disk_gb|int
  block:
    - name: Set error message
      ansible.builtin.set_fact:
        error_string: >
          "{{ se_disk_path_space.stdout | int + se_used_sysdisk | int }} GB of disk is not sufficient on {{ se_dest_disk }},
          required disk size is {{ se_disk_gb }} GB"
    - name: Include error.yml
      ansible.builtin.include_tasks: error.yml

- name: Check service engine disk size
  when: se_dest_disk and se_dest_disk|string
  block:
    - name: Check se disk in gb is greater than 0
      ansible.builtin.assert:
        that:
          - "se_disk_gb > 0"

- name: Set sys disk path
  ansible.builtin.set_fact:
    se_disk_path: "{{ se_dest_disk }}/opt/avi/se/data"
  when: se_dest_disk and se_dest_disk|string

- name: Check service engine logs disk size
  when: se_destination_log_disk and se_destination_log_disk|string
  block:
    - name: Get mount point for log disk
      ansible.builtin.shell: >
        set -o pipefail && \
        df {{ se_destination_log_disk }} -P | tail -n +2 | awk '{print $NF}'
      args:
        executable: /bin/bash
      changed_when: false
      register: se_log_mount
    - name: Get disk space on service engine logs disk path
      ansible.builtin.shell: >
        set -o pipefail && \
        df {{ se_log_mount.stdout }} -BG -P | grep -iv Used | awk '{print $4}' | sed s/G//g || true
      args:
        executable: /bin/bash
      changed_when: false
      register: se_logs_disk_path_space

- name: Check service engine logs disk usage
  when: u_logdisk_mount.stdout is defined and se_log_mount.stdout is defined and u_logdisk_mount.stdout == se_log_mount.stdout
  become: true
  block:
    - name: Axecute dokcer container
      ansible.builtin.command: "{{ se_deploy_type }} exec avise du -s -BG /vol_logs/"
      changed_when: false
      register: check_dir
    - name: Execute dokcer container
      ansible.builtin.shell: >
        set -o pipefail && \
        {{ se_deploy_type }} exec avise du -s -BG /vol_logs/ | awk '{print $1}' | sed s/G//
      args:
        executable: /bin/bash
      changed_when: false
      register: temp
      when: check_dir.rc == 0
    - name: Set se used logsd k
      ansible.builtin.set_fact:
        se_used_logsdisk: "{{ temp.stdout }}"
      changed_when: false
      when: check_dir.rc == 0

- name: Check service engine logs disk usage
  when: >
    se_destination_log_disk and se_destination_log_disk|string and
    (se_logs_disk_path_space.stdout|int + se_used_logsdisk|int) < se_logs_disk_gb|int
  block:
    - name: Set error message
      ansible.builtin.set_fact:
        error_string: >
          "{{ se_logs_disk_path_space.stdout | int + se_used_logsdisk | int }} GB of disk is not sufficient on
          {{ se_destination_log_disk }}, required disk size is {{ se_logs_disk_gb }} GB"
    - name: Include error.yml
      ansible.builtin.include_tasks: error.yml

- name: Check service engine logs disk size
  when: se_destination_log_disk and se_destination_log_disk|string
  block:
    - name: Check se_logs_disk_gb is greater that 0
      ansible.builtin.assert:
        that:
          - "se_logs_disk_gb > 0"

- name: Check service engine logs disk path
  when: >
    se_destination_log_disk and se_destination_log_disk|string and se_disk_mount.stdout == se_log_mount.stdout
    and (se_logs_disk_path_space.stdout|int + se_used_sysdisk|int + se_used_logsdisk|int) < se_logs_disk_gb|int + se_disk_gb|int
  block:
    - name: Set error message
      ansible.builtin.set_fact:
        error_string: >
          "{{ se_disk_path_space.stdout | int + se_used_sysdisk | int + se_used_logsdisk | int }} GB of disk is not sufficient,
            which is mounted on {{ se_disk_mount.stdout }}, required disk size is {{ se_disk_gb | int + se_logs_disk_gb | int }} GB"
    - name: Include error.yml
      ansible.builtin.include_tasks: error.yml

- name: Set log disk path
  ansible.builtin.set_fact:
    se_logs_disk_path: "{{ se_destination_log_disk }}/opt/avi/se/log"
  when: se_destination_log_disk and se_destination_log_disk|string
