---
- name: Set service file in systemd
  ansible.builtin.set_fact:
    service_file: /etc/systemd/system/avise.service
  when: ansible_service_mgr == "systemd"

- name: Set service file in non-systemd
  ansible.builtin.set_fact:
    service_file: /etc/init.d/avise
  when: ansible_service_mgr != "systemd"

- name: Check for exisitng avise service file
  ansible.builtin.stat:
    path: "{{ service_file }}"
  register: se_service_file

- name: "Read existing service's docker run configuration < 17.2.x"
  when: se_service_file.stat.exists
  block:
    - name: "Read existing service's docker run configuration < 17.2.x"
      ansible.builtin.shell: >
        set -o pipefail && \
        cat {{ service_file }} | sed -n -e 's/^.*docker run //p'
      args:
        executable: /bin/bash
      changed_when: false
      register: out
      when: se_deploy_type == "docker"
    - name: Read existing service's podman run configuration < 17.2.x
      ansible.builtin.shell: >
        set -o pipefail && \
        cat {{ service_file }} | sed -n -e 's/^.*podman run //p'
      args:
        executable: /bin/bash
      changed_when: false
      register: out
      when: se_deploy_type == "podman"
    - name: Check for existance of cloud uuid
      ansible.builtin.shell: >
        set -o pipefail && \
        echo {{ out.stdout }} | grep CLOUD_UUID=
      args:
        executable: /bin/bash
      changed_when: false
      register: res
      ignore_errors: true
    - name: Set se existing run params
      ansible.builtin.set_fact:
        se_existing_run_params: "{{ out.stdout }}"
      when: out.stdout is defined and res.stdout is defined and res.stdout != ""

- name: Check for existing docker run params file for 17.2.x
  when: se_existing_run_params is not defined
  block:
    - name: Check for existing docker run params file for 17.2.x
      ansible.builtin.stat:
        path: /usr/sbin/avise
      register: param_file
    - name: Read docker run params
      ansible.builtin.shell: |
          set -o pipefail
          sed -n 's/^\s*se_docker_run_params=//p' /usr/sbin/avise | tr -d '"'
      args:
          executable: /bin/bash
      changed_when: false
      register: out
      when: param_file.stat.exists
    - name: Set se existing run params
      ansible.builtin.set_fact:
        se_existing_run_params: "{{ out.stdout }}"
      when: out.stdout is defined
