---
- name: Handle error
  become: true
  block:
    - name: Printing error message from log file
      ansible.builtin.shell: "echo {{ error_string }} > /tmp/log"
      changed_when: false
    - name: Fetching log from tmp
      ansible.builtin.fetch:
        src: /tmp/log
        dest: /tmp/log
    - name: Delete log file from tmp
      ansible.builtin.file:
        path: /tmp/log
        state: absent
    - name: Set error message
      ansible.builtin.fail:
        msg: "{{ error_string }}"
