---
- name: Checks for blocking SE
  ansible.builtin.include_tasks: check_cloud.yml

- name: Check if Avi SE is running in systemd
  ansible.builtin.service:
    name: avise
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"
  register: result
  failed_when: result.rc > 0
  changed_when: false
  become: true

- name: Check if Avi SE is running in non-systemd
  ansible.builtin.service:
    name: avise_watcher
    state: started
    enabled: true
  when: ansible_service_mgr != "systemd"
  register: result
  failed_when: result.rc > 0
  changed_when: false
  become: true

- name: Check if se_agent is running
  ansible.builtin.shell: >
    set -o pipefail && \
    "ps -aef | grep se_agent | grep -v grep | wc -l"
  register: result
  failed_when: result.stdout|int != 1
  changed_when: false
  become: true
