---
- name: Checking minimum requirements
  ansible.builtin.include_tasks: requirements.yml

- name: Avi SE | Docker | Check if specified image already exists
  become: true
  ansible.builtin.shell: >
    set -o pipefail && \
    {{ se_deploy_type }} images | grep avinetworks/se | grep {{ se_version }} | wc -l || true
  changed_when: false
  register: se_docker_match

- name: Copy SE image
  when: se_docker_match.stdout | int != 1
  become: true
  block:
    - name: Copy SE image
      ansible.builtin.copy:
        src: "{{ se_package_source }}"
        dest: "{{ se_package_dest }}"
        mode: "0755"
    - name: Load docker image
      ansible.builtin.command: "{{ se_deploy_type }} load -i {{ se_package_dest }}"
      changed_when: false

- name: Enable Podman Socket
  when: se_deploy_type == "podman"
  become: true
  block:
    - name: Enable Podman Socket
      ansible.builtin.systemd:
        name: podman.socket
        enabled: true
        state: started

- name: Avi SE | Install DPDK
  ansible.builtin.include_tasks: dpdk.yml
  when: se_dpdk

- name: Avi SE | Install the Avi SE service
  ansible.builtin.include_tasks: services/install.yml
