---
# metadata file for avi controller kvm role
galaxy_info:
  author: Avi Networks <http://avinetworks.com/>
  description: Configuration for avi controller kvm
  role_name: avicontroller_kvm
  min_ansible_version: '2.9'
  license: Apache 2.0
