---
# metadata file for avise role
galaxy_info:
  author: Parikshit Manur (@pm020058) <parikshit.manur@broadcom.com>
  description: Configuration for Avi load balancer
  license: Apache 2.0
  min_ansible_version: '2.9'
  role_name: avise
