---
- name: Systemd | Deploy the avise service
  ansible.builtin.template:
    src: "{{ se_service_files_path }}avise_service.j2"
    dest: /etc/systemd/system/avise.service
    mode: "0640"
    owner: root
    group: root
  become: true
  notify:
    - Avi SE | Services | systemd | Daemon reload
    - Avi SE | Services | Restart the avise service

- name: Restorecon avise SELinux context to systemd_unit_file_t
  ansible.builtin.command: "restorecon /etc/systemd/system/avise.service -F"
  register: result
  failed_when: result.rc > 0
  changed_when: false
  become: true
  ignore_errors: true

  notify:
    - Avi SE | Services | systemd | Daemon reload
    - Avi SE | Services | Restart the avise service
